using WorkRoles.Core;

namespace WorkRoles.Core.Tests;

/// One role, frozen in code: tests stay independent of any future def edits.
public sealed record RoleSpec(
    string Name,
    string DefName,
    bool AutoAssign,
    bool Blocker,
    int MinHolders,          // def default = the resolved value in fixtures
    string[] Entries);       // "WorkType:X" / "WorkGiver:Y"

/// Phase-1 static role sets, switchable by name so the same pawns can be
/// tested against different catalogs. "Default" is a frozen copy of the
/// shipped defs (regenerate via StaticRolesGenerator when a new snapshot is
/// wanted — never silently).
public static class StaticRoles
{
    public static RoleSpec[] Default => Sets["Default"];

    /// GENERATED by StaticRolesGenerator from Roles.xml — do not hand-edit;
    /// regenerate to take a new snapshot.
    private static readonly RoleSpec[] DefaultSet =
    {
        new RoleSpec("Pyrophobe", "WS_NoFirefighting",
            AutoAssign: false, Blocker: true,
            MinHolders: -1,
            Entries: new[] { "WorkType:Firefighter" }),
        new RoleSpec("Core", "WS_Core",
            AutoAssign: true, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:Firefighter", "WorkType:Patient", "WorkGiver:DoctorRescue" }),
        new RoleSpec("Basics", "WS_Basics",
            AutoAssign: true, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:PatientBedRest", "WorkType:BasicWorker" }),
        new RoleSpec("Rescuer", "WS_Rescuer",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkGiver:DoctorRescue" }),
        new RoleSpec("Doctor", "WS_Doctor",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Doctor" }),
        new RoleSpec("Medic", "WS_Medic",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:DoctorTendEmergency", "WorkGiver:DoctorTendToHumanlikes", "WorkGiver:DoctorTendToSelf", "WorkGiver:DoctorTendToSelfEmergency", "WorkGiver:DoctorRescue", "WorkGiver:DoctorFeedHumanlikes", "WorkGiver:DoctorTendToAnimals", "WorkGiver:DoctorFeedAnimals", "WorkGiver:VisitSickPawn", "WorkGiver:ExtractBioferrite", "WorkGiver:TakeToBedToOperate", "WorkGiver:FeedHemogen", "WorkGiver:DoctorTendToEntities", "WorkGiver:DoBillsMedicalAnimalOperation" }),
        new RoleSpec("Laborer", "WS_Laborer",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:BasicWorker" }),
        new RoleSpec("Caretaker", "WS_Childminder",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Childcare" }),
        new RoleSpec("Firefighter", "WS_Firefighter",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:Firefighter" }),
        new RoleSpec("Patient", "WS_Patient",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:Patient" }),
        new RoleSpec("Bedrest", "WS_Bedrest",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:PatientBedRest" }),
        new RoleSpec("Jailor", "WS_Jailor",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:ExecuteEntity", "WorkGiver:DoExecution", "WorkGiver:ExecuteGuiltyColonist", "WorkGiver:ExecuteSlave", "WorkGiver:EmancipateSlave", "WorkGiver:ReleasePrisoner", "WorkGiver:ActivitySuppression", "WorkGiver:TakePrisonerToBed", "WorkGiver:FeedPrisoner", "WorkGiver:ImprisonSlave", "WorkGiver:DeliverHemogenToPrisoner", "WorkGiver:DeliverFoodToPrisoner", "WorkGiver:SuppressSlave", "WorkGiver:ReleaseEntity", "WorkGiver:ChatWithPrisoner" }),
        new RoleSpec("Warden", "WS_Warden",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Warden" }),
        new RoleSpec("Grunt", "WS_Grunt",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:Hauling", "WorkType:Cleaning" }),
        new RoleSpec("Hauler", "WS_Hauler",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:Hauling" }),
        new RoleSpec("Cleaner", "WS_Cleaner",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:Cleaning" }),
        new RoleSpec("Handler", "WS_Handler",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Handling" }),
        new RoleSpec("Cook", "WS_Cook",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Cooking" }),
        new RoleSpec("Butcher", "WS_Butcher",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:DoBillsButcherFlesh" }),
        new RoleSpec("Brewer", "WS_Brewer",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:DoBillsBrew" }),
        new RoleSpec("Hunter", "WS_Hunter",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkType:Hunting" }),
        new RoleSpec("Fisher", "WS_Fisher",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkType:Fishing" }),
        new RoleSpec("Builder", "WS_Builder",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Construction" }),
        new RoleSpec("Handyman", "WS_Repairer",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:Repair", "WorkGiver:FixBrokenDownBuilding", "WorkGiver:Deconstruct", "WorkGiver:DeconstructForBlueprint", "WorkGiver:Uninstall", "WorkGiver:FillIn", "WorkGiver:ConstructRemoveFloors", "WorkGiver:ConstructRemoveFoundations", "WorkGiver:BuildRoofs", "WorkGiver:RemoveRoofs", "WorkGiver:ConstructDeliverResourcesToFrames", "WorkGiver:ConstructDeliverResourcesToBlueprints", "WorkGiver:ConstructSmoothWalls", "WorkGiver:ConstructSmoothFloors" }),
        new RoleSpec("Farmer", "WS_Farmer",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Growing", "WorkType:PlantCutting" }),
        new RoleSpec("Grower", "WS_Grower",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkType:Growing" }),
        new RoleSpec("Plant Cutter", "WS_PlantCutter",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkType:PlantCutting" }),
        new RoleSpec("Miner", "WS_Miner",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Mining" }),
        new RoleSpec("Tailor", "WS_Tailor",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Tailoring" }),
        new RoleSpec("Smith", "WS_Smith",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Smithing" }),
        new RoleSpec("Fabricator", "WS_Fabricator",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkGiver:DoBillsFabricationBench" }),
        new RoleSpec("Crafter", "WS_Crafter",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Crafting" }),
        new RoleSpec("Researcher", "WS_Researcher",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:Research" }),
        new RoleSpec("Anomalist", "WS_DarkStudier",
            AutoAssign: false, Blocker: false,
            MinHolders: 1,
            Entries: new[] { "WorkType:DarkStudy" }),
        new RoleSpec("Artist", "WS_Artist",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkType:Art" }),
        new RoleSpec("Nurse", "WS_Nurse",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:DoctorTendToSelfEmergency", "WorkGiver:DoctorRescue", "WorkGiver:DoctorFeedHumanlikes", "WorkGiver:DoctorTendToAnimals", "WorkGiver:DoctorFeedAnimals", "WorkGiver:VisitSickPawn", "WorkGiver:TakeToBedToOperate", "WorkGiver:FeedHemogen", "WorkGiver:ExtractBioferrite" }),
        new RoleSpec("Drug Maker", "WS_DrugMaker",
            AutoAssign: false, Blocker: false,
            MinHolders: -1,
            Entries: new[] { "WorkGiver:DoBillsProduceDrugs", "WorkGiver:DoBillsSerumCentrifuge" }),
        new RoleSpec("Painter", "WS_Painter",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:RemovePaintBuilding", "WorkGiver:RemovePaintFloor", "WorkGiver:PaintBuilding", "WorkGiver:PaintFloor" }),
        new RoleSpec("Herder", "WS_Herder",
            AutoAssign: false, Blocker: false,
            MinHolders: 0,
            Entries: new[] { "WorkGiver:TakeRoamingAnimalsToPen", "WorkGiver:HandlingFeedPatientAnimals", "WorkGiver:TakeToPen", "WorkGiver:Slaughter", "WorkGiver:ReleaseToWild", "WorkGiver:Milk", "WorkGiver:Shear", "WorkGiver:RebalanceAnimalsInPens" }),
    };

    /// Static fields initialize in TEXTUAL order: the generated set below
    /// must stay above this dictionary.
    public static readonly IReadOnlyDictionary<string, RoleSpec[]> Sets =
        new Dictionary<string, RoleSpec[]>
        {
            ["Default"] = DefaultSet,
        };

    /// The vanilla job catalog the entries expand through.
    public static readonly FakeCatalog JobCatalog = BuildJobCatalog();

    private static FakeCatalog BuildJobCatalog()
    {
        var catalog = new FakeCatalog();
        foreach (var group in VanillaGiverBaseline.GiverWorkType.GroupBy(kv => kv.Value))
            catalog.WithWorkType(group.Key, group.Select(kv => kv.Key).ToArray());
        return catalog;
    }

    public static List<JobEntry> ParsedEntries(RoleSpec spec)
    {
        var entries = new List<JobEntry>();
        foreach (var raw in spec.Entries)
            if (JobEntry.TryDecode(raw, out var entry)) entries.Add(entry);
        return entries;
    }

    public static List<string> WorkTypesOf(RoleSpec spec)
    {
        var workTypes = new List<string>();
        foreach (var entry in ParsedEntries(spec))
        {
            string workType = entry.Kind == JobEntryKind.WorkType ? entry.DefName
                : VanillaGiverBaseline.GiverWorkType.TryGetValue(entry.DefName, out var parent)
                    ? parent : null;
            if (workType != null && !workTypes.Contains(workType)) workTypes.Add(workType);
        }
        return workTypes;
    }

    /// Test-side primary skill: most frequent work-type relevant skill across
    /// the coverage (the game adapter uses the accurate XP tables instead).
    public static string PrimarySkillOf(RoleSpec spec)
    {
        var counts = new Dictionary<string, int>();
        foreach (var giver in CoverageMath.CoverageOf(ParsedEntries(spec), JobCatalog))
            if (VanillaGiverBaseline.GiverWorkType.TryGetValue(giver, out var wt)
                && ColonyScenarioTests.SkillsByWorkType.TryGetValue(wt, out var skills))
                foreach (var s in skills)
                    counts[s] = counts.TryGetValue(s, out int c) ? c + 1 : 1;
        return counts.Count == 0 ? null
            : counts.OrderByDescending(kv => kv.Value)
                .ThenBy(kv => kv.Key, StringComparer.Ordinal).First().Key;
    }

    /// Projects a set into the engine shape (ids = table order, 1-based).
    public static List<WorkRoles.Core.Recs.RoleView> ToRoleViews(IReadOnlyList<RoleSpec> set)
    {
        var roles = new List<WorkRoles.Core.Recs.RoleView>();
        for (int i = 0; i < set.Count; i++)
        {
            var spec = set[i];
            var entries = ParsedEntries(spec);
            var workTypes = WorkTypesOf(spec);
            var role = new WorkRoles.Core.Recs.RoleView
            {
                Id = i + 1,
                Coverage = CoverageMath.CoverageOf(entries, JobCatalog),
                OrderedCoverage = CoverageMath.OrderedCoverageOf(entries, JobCatalog),
                AutoAssign = spec.AutoAssign,
                Blocker = spec.Blocker,
                Unskilled = workTypes.All(wt => !ColonyScenarioTests.SkillsByWorkType.ContainsKey(wt)),
                Hunting = workTypes.Contains("Hunting"),
                NaturalPriority = workTypes
                    .Select(wt => VanillaWorkOrder.NaturalPriority.TryGetValue(wt, out int p) ? p : 0)
                    .DefaultIfEmpty(0).Max(),
                MinHolders = spec.MinHolders,
                PrimarySkill = PrimarySkillOf(spec),
            };
            role.WorkTypes.AddRange(workTypes);
            roles.Add(role);
        }
        return roles;
    }
}
