using WorkRoles.Core;

namespace WorkRoles.Core.Tests;

/// Attribute kinds are flags: any skill-level effect a trait or aptitude has
/// is already baked into the pawn's level numbers.
public enum AttributeKind
{
    Expertise,       // VSE expertise on the skill
    Aptitude,        // talented at the skill (positive-attitude signal)
    BurningPassion,  // vanilla major passion
    Passion,         // vanilla minor passion
    Trait,           // apathy: hates using the skill (mutes its signals)
}

public sealed record PawnAttribute(AttributeKind Kind, string Skill);

public sealed record PawnSpec(string Name, int[] Levels, PawnAttribute[] Attributes, bool HasGun);

/// Phase-1 static input data: a fixed 20-pawn colony (regenerate via
/// StaticColonyGenerator, paste the emitted table over Pawns), the vanilla
/// work-type/giver tables (VanillaWorkOrder — already code), and the
/// flatten/best-in-colony helpers the pipeline consumes.
public static class StaticColony
{
    /// The 12 vanilla skills; PawnSpec.Levels is indexed by this order.
    public static readonly string[] Skills =
    {
        "Shooting", "Melee", "Construction", "Mining", "Cooking", "Plants",
        "Animals", "Crafting", "Artistic", "Medicine", "Social", "Intellectual",
    };

    /// Every vanilla work type (single location; all pawns capable of all).
    public static IEnumerable<string> AllWorkTypes => VanillaWorkOrder.NaturalPriority.Keys;

    /// workType -> relevant skills, shared with the scenario suite.
    public static IReadOnlyDictionary<string, IReadOnlyList<string>> WorkTypeSkills
        => ColonyScenarioTests.SkillsByWorkType;

    /// GENERATED by StaticColonyGenerator (seed 20260716) — do not hand-edit
    /// values; regenerate instead.
    public static readonly PawnSpec[] Pawns =
    {
        new PawnSpec("Alva",
            new[] { 3, 3, 3, 4, 3, 3, 3, 0, 3, 1, 4, 4 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Shooting"),
                new PawnAttribute(AttributeKind.Expertise, "Cooking"),
                new PawnAttribute(AttributeKind.Passion, "Social"),
                new PawnAttribute(AttributeKind.Expertise, "Crafting"),
            },
            false),
        new PawnSpec("Brik",
            new[] { 3, 5, 1, 14, 11, 3, 9, 11, 7, 10, 8, 11 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Mining"),
                new PawnAttribute(AttributeKind.BurningPassion, "Artistic"),
                new PawnAttribute(AttributeKind.Expertise, "Medicine"),
                new PawnAttribute(AttributeKind.Expertise, "Social"),
            },
            true),
        new PawnSpec("Cass",
            new[] { 8, 12, 3, 3, 11, 5, 15, 5, 10, 11, 3, 13 },
            new[]
            {
                new PawnAttribute(AttributeKind.Aptitude, "Construction"),
                new PawnAttribute(AttributeKind.Passion, "Intellectual"),
                new PawnAttribute(AttributeKind.Trait, "Mining"),
                new PawnAttribute(AttributeKind.Passion, "Construction"),
            },
            true),
        new PawnSpec("Dolf",
            new[] { 2, 7, 7, 8, 5, 0, 3, 0, 9, 1, 0, 4 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Plants"),
                new PawnAttribute(AttributeKind.Trait, "Cooking"),
                new PawnAttribute(AttributeKind.Trait, "Mining"),
                new PawnAttribute(AttributeKind.Expertise, "Shooting"),
            },
            true),
        new PawnSpec("Edda",
            new[] { 14, 5, 1, 3, 13, 11, 6, 1, 4, 2, 4, 4 },
            new[]
            {
                new PawnAttribute(AttributeKind.Passion, "Crafting"),
                new PawnAttribute(AttributeKind.Aptitude, "Artistic"),
                new PawnAttribute(AttributeKind.BurningPassion, "Construction"),
                new PawnAttribute(AttributeKind.Trait, "Melee"),
            },
            true),
        new PawnSpec("Finn",
            new[] { 2, 0, 8, 8, 8, 2, 17, 8, 0, 3, 7, 7 },
            new[]
            {
                new PawnAttribute(AttributeKind.Trait, "Animals"),
                new PawnAttribute(AttributeKind.Aptitude, "Medicine"),
                new PawnAttribute(AttributeKind.BurningPassion, "Intellectual"),
                new PawnAttribute(AttributeKind.Expertise, "Intellectual"),
            },
            false),
        new PawnSpec("Gwen",
            new[] { 7, 2, 9, 2, 8, 9, 1, 4, 4, 7, 2, 0 },
            new[]
            {
                new PawnAttribute(AttributeKind.Passion, "Plants"),
                new PawnAttribute(AttributeKind.Aptitude, "Mining"),
                new PawnAttribute(AttributeKind.Expertise, "Medicine"),
                new PawnAttribute(AttributeKind.Expertise, "Melee"),
            },
            true),
        new PawnSpec("Hark",
            new[] { 10, 12, 12, 13, 12, 1, 7, 9, 1, 2, 9, 2 },
            new[]
            {
                new PawnAttribute(AttributeKind.Passion, "Mining"),
                new PawnAttribute(AttributeKind.Expertise, "Artistic"),
                new PawnAttribute(AttributeKind.Passion, "Melee"),
                new PawnAttribute(AttributeKind.Expertise, "Intellectual"),
            },
            true),
        new PawnSpec("Iris",
            new[] { 4, 12, 12, 13, 8, 4, 12, 4, 12, 3, 6, 6 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Melee"),
                new PawnAttribute(AttributeKind.Aptitude, "Intellectual"),
                new PawnAttribute(AttributeKind.Expertise, "Shooting"),
                new PawnAttribute(AttributeKind.Trait, "Medicine"),
            },
            true),
        new PawnSpec("Jorn",
            new[] { 6, 9, 11, 16, 3, 5, 3, 1, 1, 14, 6, 10 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Shooting"),
                new PawnAttribute(AttributeKind.Expertise, "Intellectual"),
                new PawnAttribute(AttributeKind.BurningPassion, "Construction"),
                new PawnAttribute(AttributeKind.Passion, "Medicine"),
            },
            false),
        new PawnSpec("Kaya",
            new[] { 7, 3, 8, 9, 3, 7, 1, 9, 0, 1, 3, 1 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Mining"),
                new PawnAttribute(AttributeKind.Expertise, "Animals"),
                new PawnAttribute(AttributeKind.Expertise, "Medicine"),
                new PawnAttribute(AttributeKind.Expertise, "Social"),
            },
            true),
        new PawnSpec("Lund",
            new[] { 9, 1, 5, 7, 1, 10, 8, 9, 9, 5, 2, 2 },
            new[]
            {
                new PawnAttribute(AttributeKind.Trait, "Plants"),
                new PawnAttribute(AttributeKind.Trait, "Melee"),
                new PawnAttribute(AttributeKind.Trait, "Mining"),
                new PawnAttribute(AttributeKind.BurningPassion, "Artistic"),
            },
            true),
        new PawnSpec("Mira",
            new[] { 0, 1, 11, 7, 2, 0, 2, 20, 5, 0, 15, 20 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Cooking"),
                new PawnAttribute(AttributeKind.Expertise, "Cooking"),
                new PawnAttribute(AttributeKind.Aptitude, "Animals"),
                new PawnAttribute(AttributeKind.BurningPassion, "Artistic"),
            },
            true),
        new PawnSpec("Nils",
            new[] { 5, 6, 10, 0, 7, 8, 5, 0, 9, 1, 2, 4 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Social"),
                new PawnAttribute(AttributeKind.Aptitude, "Mining"),
                new PawnAttribute(AttributeKind.Passion, "Medicine"),
                new PawnAttribute(AttributeKind.Aptitude, "Construction"),
            },
            false),
        new PawnSpec("Osla",
            new[] { 15, 0, 14, 9, 4, 20, 2, 0, 4, 0, 12, 3 },
            new[]
            {
                new PawnAttribute(AttributeKind.Passion, "Shooting"),
                new PawnAttribute(AttributeKind.Passion, "Construction"),
                new PawnAttribute(AttributeKind.BurningPassion, "Animals"),
                new PawnAttribute(AttributeKind.Aptitude, "Cooking"),
            },
            true),
        new PawnSpec("Piet",
            new[] { 4, 11, 8, 0, 0, 0, 10, 5, 3, 1, 0, 4 },
            new[]
            {
                new PawnAttribute(AttributeKind.Trait, "Artistic"),
                new PawnAttribute(AttributeKind.BurningPassion, "Construction"),
                new PawnAttribute(AttributeKind.BurningPassion, "Crafting"),
                new PawnAttribute(AttributeKind.Trait, "Medicine"),
            },
            true),
        new PawnSpec("Quin",
            new[] { 15, 6, 4, 4, 9, 7, 5, 11, 14, 6, 12, 1 },
            new[]
            {
                new PawnAttribute(AttributeKind.BurningPassion, "Artistic"),
                new PawnAttribute(AttributeKind.Passion, "Melee"),
                new PawnAttribute(AttributeKind.Trait, "Shooting"),
                new PawnAttribute(AttributeKind.Expertise, "Crafting"),
            },
            true),
        new PawnSpec("Rask",
            new[] { 1, 1, 1, 0, 13, 4, 2, 12, 7, 8, 11, 5 },
            new[]
            {
                new PawnAttribute(AttributeKind.Expertise, "Plants"),
                new PawnAttribute(AttributeKind.Trait, "Medicine"),
                new PawnAttribute(AttributeKind.BurningPassion, "Animals"),
                new PawnAttribute(AttributeKind.Aptitude, "Social"),
            },
            true),
        new PawnSpec("Sune",
            new[] { 7, 9, 1, 5, 2, 0, 6, 8, 4, 1, 7, 3 },
            new[]
            {
                new PawnAttribute(AttributeKind.Aptitude, "Melee"),
                new PawnAttribute(AttributeKind.Aptitude, "Animals"),
                new PawnAttribute(AttributeKind.BurningPassion, "Melee"),
                new PawnAttribute(AttributeKind.Trait, "Mining"),
            },
            true),
        new PawnSpec("Tova",
            new[] { 9, 4, 4, 2, 7, 8, 4, 9, 1, 4, 3, 2 },
            new[]
            {
                new PawnAttribute(AttributeKind.Passion, "Melee"),
                new PawnAttribute(AttributeKind.Passion, "Social"),
                new PawnAttribute(AttributeKind.Trait, "Animals"),
                new PawnAttribute(AttributeKind.Trait, "Cooking"),
            },
            true),
    };

    /// Flattens a spec into the engine's pawn shape — the step-1 projection,
    /// test-side. Attitude flags map to the engine's aptitude sign: talented
    /// = +1, apathy = -1 (magnitudes carry no meaning of their own).
    public static RecPawn ToRecPawn(PawnSpec spec)
    {
        var pawn = new RecPawn
        {
            HasRangedWeapon = spec.HasGun,
        };
        for (int i = 0; i < Skills.Length; i++)
            pawn.SkillLevels[Skills[i]] = spec.Levels[i];
        pawn.ShootingLevel = spec.Levels[0];
        foreach (var attribute in spec.Attributes)
        {
            switch (attribute.Kind)
            {
                case AttributeKind.Expertise:
                    pawn.ExpertiseSkills.Add(attribute.Skill);
                    break;
                case AttributeKind.BurningPassion:
                    pawn.PassionScores[attribute.Skill] = 2;
                    break;
                case AttributeKind.Passion:
                    pawn.PassionScores[attribute.Skill] = 1;
                    break;
                case AttributeKind.Aptitude:
                    pawn.Aptitudes[attribute.Skill] = 1;
                    break;
                case AttributeKind.Trait:
                    pawn.Aptitudes[attribute.Skill] = -1;
                    break;
            }
        }
        foreach (var workType in AllWorkTypes)
            pawn.CapableWorkTypes.Add(workType);
        return pawn;
    }

    /// Best-in-colony: the highest level per skill across the colony.
    public static Dictionary<string, int> BestInColony(IEnumerable<PawnSpec> pawns)
    {
        var best = new Dictionary<string, int>();
        foreach (var spec in pawns)
            for (int i = 0; i < Skills.Length; i++)
                if (!best.TryGetValue(Skills[i], out int max) || spec.Levels[i] > max)
                    best[Skills[i]] = spec.Levels[i];
        return best;
    }
}
