using System.Collections.Generic;

namespace WorkRoles.Core
{
    /// Skills each vanilla/DLC non-bill giver actually grants XP in —
    /// verified against decompiled JobDriver/verb code (the game wires XP in
    /// code, defs carry no XP data). Empty = the work grants no XP. Curated
    /// mod data consumed by the live JobSkillProfiles index and by the
    /// offline vanilla baseline generator.
    public static class VanillaXpBaseline
    {
        public static readonly Dictionary<string, string[]> XpByGiver = new Dictionary<string, string[]>
        {
            // Core
            ["FightFires"] = new string[0],
            ["PatientGoToBedEmergencyTreatment"] = new string[0],
            ["PatientGoToBedTreatment"] = new string[0],
            ["DoctorTendEmergency"] = new[] { "Medicine" },
            ["DoctorTendToHumanlikes"] = new[] { "Medicine" },
            ["DoctorTendToSelf"] = new[] { "Medicine" },
            ["DoctorTendToSelfEmergency"] = new[] { "Medicine" },
            ["DoctorFeedHumanlikes"] = new string[0],
            ["DoctorRescue"] = new string[0],
            ["DoctorTendToAnimals"] = new[] { "Medicine" },
            ["DoctorFeedAnimals"] = new string[0],
            ["TakeToBedToOperate"] = new string[0],
            ["VisitSickPawn"] = new string[0],
            ["PatientGoToBedRecuperate"] = new string[0],
            ["Flick"] = new string[0],
            ["BasicReleasePrisoner"] = new string[0],
            ["Open"] = new string[0],
            ["EjectFuel"] = new string[0],
            ["ExtractSkull"] = new string[0],
            ["DoExecution"] = new string[0],
            ["ExecuteGuiltyColonist"] = new string[0],
            ["ReleasePrisoner"] = new string[0],
            ["TakePrisonerToBed"] = new string[0],
            ["FeedPrisoner"] = new string[0],
            ["DeliverFoodToPrisoner"] = new string[0],
            ["ChatWithPrisoner"] = new[] { "Social" },
            ["TakeRoamingAnimalsToPen"] = new string[0],
            ["HandlingFeedPatientAnimals"] = new string[0],
            ["TakeToPen"] = new string[0],
            ["Slaughter"] = new string[0],
            ["ReleaseToWild"] = new string[0],
            ["Milk"] = new[] { "Animals" },
            ["Shear"] = new[] { "Animals" },
            ["Tame"] = new[] { "Animals" },
            ["Train"] = new[] { "Animals" },
            ["RebalanceAnimalsInPens"] = new string[0],
            // Finish-off (Allow Tool, Keyz' Allow Utilities): an execution-style
            // instant kill, no XP (same footing as Slaughter/DoExecution).
            ["FinishOff"] = new string[0],
            ["KAU_FinishOff"] = new string[0],
            ["CookFillHopper"] = new string[0],
            ["HunterHunt"] = new[] { "Shooting" },
            ["FixBrokenDownBuilding"] = new string[0],
            ["Uninstall"] = new string[0],
            ["ExtractTree"] = new[] { "Plants" },
            ["BuildRoofs"] = new string[0],
            ["RemoveRoofs"] = new string[0],
            ["DeconstructForBlueprint"] = new[] { "Construction" },
            ["ConstructFinishFrames"] = new[] { "Construction" },
            ["ConstructDeliverResourcesToFrames"] = new string[0],
            ["ConstructDeliverResourcesToBlueprints"] = new[] { "Construction" },
            ["Replant"] = new[] { "Plants" },
            ["FillIn"] = new string[0],
            ["Deconstruct"] = new[] { "Construction" },
            ["Repair"] = new[] { "Construction" },
            ["PaintBuilding"] = new[] { "Artistic" },
            ["PaintFloor"] = new[] { "Artistic" },
            ["RemovePaintBuilding"] = new string[0],
            ["RemovePaintFloor"] = new string[0],
            ["ConstructRemoveFloors"] = new[] { "Construction" },
            ["ConstructRemoveFoundations"] = new[] { "Construction" },
            ["ConstructSmoothFloors"] = new[] { "Construction" },
            ["ConstructSmoothWalls"] = new[] { "Construction" },
            ["GrowerHarvest"] = new[] { "Plants" },
            ["GrowerSow"] = new[] { "Plants" },
            ["Mine"] = new[] { "Mining" },
            ["Drill"] = new[] { "Mining" },
            ["PlantsCut"] = new[] { "Plants" },
            ["RearmTurrets"] = new string[0],
            ["Refuel"] = new string[0],
            ["UnloadCarriers"] = new string[0],
            ["HelpGatheringItemsForCaravan"] = new string[0],
            ["LoadTransporters"] = new string[0],
            ["HaulToPortal"] = new string[0],
            ["Strip"] = new string[0],
            ["HaulCorpses"] = new string[0],
            ["TakeBeerOutOfFermentingBarrel"] = new string[0],
            ["FillFermentingBarrel"] = new string[0],
            ["HaulGeneral"] = new string[0],
            ["DeliverResourcesToFrames"] = new string[0],
            ["DeliverResourcesToBlueprints"] = new string[0],
            ["HaulMerge"] = new string[0],
            ["EmptyEggBox"] = new string[0],
            ["CleanClearSnow"] = new string[0],
            ["CleanFilth"] = new string[0],
            ["Research"] = new[] { "Intellectual" },
            ["LongRangeScan"] = new[] { "Intellectual" },
            ["GroundPenetratingScan"] = new[] { "Intellectual" },
            ["PlantSeed"] = new[] { "Plants" },
            ["StudyArchotechStructures"] = new[] { "Intellectual" },
            ["Hack"] = new[] { "Intellectual" },
            // Ideology
            ["ExecuteSlave"] = new string[0],
            ["EmancipateSlave"] = new string[0],
            ["EnslavePrisoner"] = new[] { "Social" },
            ["ImprisonSlave"] = new string[0],
            ["SuppressSlave"] = new string[0],
            ["ConvertPrisoner"] = new[] { "Social" },
            ["PruneGauranlenTree"] = new[] { "Plants" },
            ["ChangeTreeMode"] = new string[0],
            ["HaulToBiosculpterPod"] = new string[0],
            // Biotech
            ["DeliverHemogenToPrisoner"] = new string[0],
            ["FeedHemogen"] = new string[0],
            ["HaulToGeneBank"] = new string[0],
            ["CreateXenogerm"] = new[] { "Intellectual" },
            ["EnterGeneExtractor"] = new string[0],
            ["EnterGrowthVat"] = new string[0],
            ["CarryToGeneExtractor"] = new string[0],
            ["CarryToGrowthVat"] = new string[0],
            ["BringBabyToSafety"] = new string[0],
            ["BreastfeedBaby"] = new string[0],
            ["PlayWithBaby"] = new string[0],
            ["BottleFeedBaby"] = new string[0],
            ["CarryToBreastfeed"] = new string[0],
            ["ChildcarerTeach"] = new[] { "Social" },
            ["HaulToGrowthVat"] = new string[0],
            ["RepairMech"] = new[] { "Crafting" },
            ["EmptyWasteContainer"] = new string[0],
            ["HaulMechsToCharger"] = new string[0],
            ["EnterSubcoreScanner"] = new string[0],
            ["CarryToSubcoreScanner"] = new string[0],
            ["HaulToCarrier"] = new string[0],
            ["HaulToSubcoreScanner"] = new string[0],
            ["HaulToWastepackAtomizer"] = new string[0],
            ["CleanClearPollution"] = new string[0],
            // Anomaly
            ["TakeEntityToHoldingPlatform"] = new string[0],
            ["ReleaseEntity"] = new string[0],
            ["TransferEntity"] = new string[0],
            ["ActivitySuppression"] = new[] { "Intellectual" },
            ["ExecuteEntity"] = new string[0],
            ["InterrogatePrisoner"] = new[] { "Social" },
            ["TakeBioferriteOutOfHarvester"] = new string[0],
            ["DoctorTendToEntities"] = new[] { "Medicine" },
            ["ExtractBioferrite"] = new string[0],
            ["StudyInteract"] = new[] { "Intellectual" },
            // Odyssey
            ["Fish"] = new[] { "Animals" },
        };
    }
}
